# ~/.streamlit/config.toml

[theme]
base="dark"
primaryColor="#FF4B4B"  # Couleur principale pour les boutons et éléments interactifs
backgroundColor="#0E1117"  # Fond sombre pour l'ensemble de l'application
secondaryBackgroundColor="#1C1F24"  # Fond secondaire pour les sections distinctes
textColor="#39FF14"  # Texte vert fluo pour le style hacker
font="monospace"  # Style terminal pour le texte

# Personnalisation supplémentaire des en-têtes et autres éléments
headerColor="#FF4B4B"
headerTextColor="#FFFFFF"
codeTextColor="#FF4B4B"
errorTextColor="#FF0000"
infoTextColor="#39FF14"
warningTextColor="#FFA500"
borderRadius="10px"
buttonBorderColor="#FF4B4B"
inputBorderColor="#39FF14"
progressColor="#FF4B4B"

[sidebar]
backgroundColor="#1A1D21"
textColor="#39FF14"
headerColor="#FF4B4B"
